services:
  # Go
  backend:
    build:
      context: backend
      target: builder
    secrets:
      - db-password
    networks:
      - public
      - private
    depends_on:
      db:
        condition: service_healthy
    restart: always

  # MySQL
  db:
    image: mysql:8
    command: "--default-authentication-plugin=mysql_native_password --general-log=1 --general-log-file=/var/log/mysql/mysql.log"
    healthcheck:
      test:
        [
          "CMD-SHELL",
          'mysqladmin ping -h 127.0.0.1 --password="$$(cat /run/secrets/db-password)" --silent',
        ]
      interval: 3s
      retries: 5
      start_period: 30s
    secrets:
      - db-password
    networks:
      - private
    volumes:
      - db-data:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=example
      - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/db-password
    expose:
      - 3306
    ports:
      - 3306:3306
    restart: always

  # React
  frontend:
    build:
      context: frontend
    expose:
      - 3000
    volumes:
      - ./frontend/src:/code/src
      - /code/node_modules
    networks:
      - public
    env_file:
      - path: ./frontend/.env.local
        required: true
    depends_on:
      - backend
    restart: always

  # Nginx
  proxy:
    image: nginx
    volumes:
      - type: bind
        source: ./proxy/nginx.conf
        target: /etc/nginx/conf.d/default.conf
        read_only: true
    networks:
      - public
    ports:
      - 80:80
      - 8080:8080
      - 3000:80
    depends_on:
      - backend
      - frontend
    restart: always

networks:
  public:
  private:

volumes:
  db-data:

secrets:
  db-password:
    file: db/password.txt
